---
title: "Using 911 Data to Understand Police Deployment"
format:
  gfm:
    fig-width: 6
    fig-height: 4
execute:
  echo: false
  warning: false
  message: false
---


In January this year—in response to [widespread concerns](https://www.vitalcitynyc.org/articles/what-to-do-about-subway-safety-nyc-policy-recommendations) about safety on the New York City subway—the New York City Police Department (NYPD) [announced a new policy](https://ny1.com/nyc/all-boroughs/news/2025/01/16/nypd-to-deploy-1-050-more-officers-into-subway-stations--hochul-says): the city would add hundreds of officers to patrol the city's subways, including two officers for each of the city's 150 late-night subway trains that run between 9pm and 5am.

How can we know if the city kept its promise? You might think that we would need to file a public records request with the NYPD to get data on every officer that signed in to a transit precinct between 9pm and 5am. But it turns out that the NYPD already publishes data online—for anyone to download and analyze—that allows us to understand highly granular patrol activity. It's the city's "Calls for Service"—i.e., 911—dataset.

It might seem counterintuitive that a 911 dataset would include information on where officers are deployed. But when you dial 911, the call is typically routed to a calltaker, who takes your information and then passes it off to a dispatcher. Dispatchers have a tough job: they have to keep track of the current location for dozens of officers, so that they can find nearby officers for a new call—especially if it's urgent. To help dispatchers keep track of where they are, officers will routinely and proactively check-in with their dispatcher via their radio with an update on their current status. These check-ins are recorded as "calls" in the "Calls for Service" dataset alongside 911 calls from the public, and they are the key to understanding and analyzing officer deployment.

Calls for service (CFS) data is available to download from the city's Open Data portal. The data is posted in two parts. The first is a dataset of [historic CFS](#0) from TKTK to the end of last year. The second dataset contains [year-to-date CFS](#0), updated roughly every quarter. As of this blog post, the year-to-date data contains records up to July 2025. Altogether, there are {nearly,over} 50 million records in the data, underscoring the potential to use these datasets for precise statistical analysis.

NYPD's CFS dataset includes a wealth of information: 
location information, including the precinct, borough, patrol borough, and the latitude/longitude where the call took place; 
timestamp information, including the time and date of the underlying incident (e.g., in the event of a call from the public), as well as timestamps for when the call was added to the database, when an officer was dispatched, when they arrived at the scene, and when they closed out the call; 
information on the type of call, including the "radio code"—a 2–3 alphanumeric code that officers say to indicate what they're doing; 
and corresponding description for the radio code. These codes can be quite cryptic—e.g., "75M" means that officers are initiating patrol of a subway train—so we found a training guide for new officers that includes detailed descriptions of the codes, and [posted it](https://github.com/chohlasa/asa-911-blog-post/blob/main/docs/NYPD%20Police%20Student%20Guide%20(December%202020-February%202021).pdf) in our GitHub repository.

To understand whether the city really did add officers to patrol trains overnight, we examined the number of calls where officers checked in from a subway station between 9pm and 5am with radio code "75M", indicating a pending patrol of a subway train. We compared these check-ins before and after the policy announcement in January of 2025.

Many other cities, including Seattle, San Francisco, ... , make similar data available online.

